//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<decimal> Purse { get; set; }
        public Nullable<decimal> TempPurse { get; set; }
        public Nullable<decimal> Withdrawals { get; set; }
        public Nullable<decimal> Admin2 { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
