//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public int ID { get; set; }
        public Nullable<decimal> CourseFees { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<decimal> RegistrationFee2 { get; set; }
        public string DefaultReferralCode { get; set; }
        public Nullable<decimal> ReferralCodeEarning { get; set; }
        public Nullable<int> MaxUnderline { get; set; }
        public Nullable<int> MaxFirstLevel { get; set; }
        public Nullable<decimal> MinSubscriptionAmt { get; set; }
        public Nullable<double> CompRegPercent { get; set; }
        public Nullable<double> CompSubPercent { get; set; }
        public Nullable<int> CurrentSemester { get; set; }
        public Nullable<int> CurrentSession { get; set; }
        public Nullable<decimal> NoReferralAmount { get; set; }
        public Nullable<int> MaximumOptions { get; set; }
        public Nullable<int> QuestionsBatches { get; set; }
        public Nullable<double> PRYQuizPeriod { get; set; }
        public Nullable<double> JSSQuizPeriod { get; set; }
        public Nullable<double> SSSQuizPeriod { get; set; }
        public Nullable<double> QuizPeriod { get; set; }
        public Nullable<double> MockPeriod { get; set; }
        public string SupportPhone { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
