//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CArumala_edquizEntities : DbContext
    {
        public CArumala_edquizEntities()
            : base("name=CArumala_edquizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<BankInfo> BankInfos { get; set; }
        public virtual DbSet<ClientPayment> ClientPayments { get; set; }
        public virtual DbSet<ClientQuestion> ClientQuestions { get; set; }
        public virtual DbSet<ClientQuiz> ClientQuizs { get; set; }
        public virtual DbSet<ClientSetting> ClientSettings { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Downline> Downlines { get; set; }
        public virtual DbSet<DurationInMonth> DurationInMonths { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<PastQuestion> PastQuestions { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual DbSet<Percentage> Percentages { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<QuestionMark> QuestionMarks { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SiteMenu> SiteMenus { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<AcademicClass> AcademicClasses { get; set; }
        public virtual DbSet<BankPayment> BankPayments { get; set; }
        public virtual DbSet<BANK> BANKS { get; set; }
        public virtual DbSet<Commission> Commissions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CourseDepartment> CourseDepartments { get; set; }
        public virtual DbSet<CoursePlu> CoursePlus { get; set; }
        public virtual DbSet<FailedRegistration> FailedRegistrations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<MDetail> MDetails { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Student_Details> Student_Details { get; set; }
        public virtual DbSet<StudentCours> StudentCourses { get; set; }
        public virtual DbSet<StudentPayment> StudentPayments { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<FreeTrial> FreeTrials { get; set; }
        public virtual DbSet<FreeTrialQuiz> FreeTrialQuizs { get; set; }
        public virtual DbSet<FreeTrialQuestion> FreeTrialQuestions { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
    }
}
