//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientQuiz
    {
        public long ClientQuizID { get; set; }
        public string Token { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> ResourceTypeID { get; set; }
        public Nullable<int> QuestionCount { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> LastQuestionID { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
