//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSetting
    {
        public int UserSettingID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<int> WithdrawalPercent { get; set; }
        public Nullable<System.DateTime> Craeted { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
