//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeTrialQuiz
    {
        public long FreeTrialQuizID { get; set; }
        public Nullable<long> FreeTrialID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string QuizName { get; set; }
        public Nullable<int> QuizDuration { get; set; }
        public Nullable<int> QueCount { get; set; }
        public Nullable<int> QuestionsAttempted { get; set; }
        public Nullable<double> Score { get; set; }
        public string TimeSpent { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failure { get; set; }
    }
}
