//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDetail
    {
        public int MDetailID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<byte> AccountTypeID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string CVV { get; set; }
        public Nullable<bool> DefaultAccount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
