//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public long PaymentTransactionID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public string RefereeCode { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> NLevel { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> TempFlag { get; set; }
        public Nullable<bool> AcctFlag { get; set; }
        public Nullable<bool> ToCompanyFlag { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
