//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<int> NetworkID { get; set; }
        public Nullable<long> ReferralID { get; set; }
        public Nullable<long> DirectReferralID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Mode { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
