//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long PersonID { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<int> AcademicClassID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> PayMode { get; set; }
        public string RefereeCode { get; set; }
        public string ParentCode { get; set; }
        public Nullable<long> ActiveSubscriptionID { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<int> MaxFirstLevel { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
