//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QuestionID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public Nullable<int> ResourceTypeID { get; set; }
        public Nullable<int> CoursePlusID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
        public string Number { get; set; }
        public string QuestionString { get; set; }
        public string Answer { get; set; }
        public Nullable<int> QuestionMarks { get; set; }
        public string CorrectAnswer { get; set; }
        public string AnswerExplanation { get; set; }
        public Nullable<int> QuestionDuration { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Instruction { get; set; }
        public Nullable<bool> IsMock { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> FIGSlot { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> InserterID { get; set; }
        public Nullable<long> UpdaterID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string FIGAnswer1 { get; set; }
        public string FIGAnswer2 { get; set; }
        public Nullable<bool> IsFree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
