//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        public long StudentCourseID { get; set; }
        public Nullable<long> StudentDetailID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> TutorialScore { get; set; }
        public Nullable<double> ExamScore { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
