//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace braingainspa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public Nullable<byte> StatusTypeID { get; set; }
        public Nullable<byte> FirstTimeLogin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ConfirmEmail { get; set; }
        public Nullable<bool> ConfirmPhone { get; set; }
        public string PhoneCode { get; set; }
        public string EmailCode { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public Nullable<bool> Deactivated { get; set; }
        public string LoginCode { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
